import pool from './pool.js';
import useDb from './useDb.js';
import { DB_NAME } from '../../env.js';
// Poblamos base de datos para pruebas
const populateDb = async () => {
  try {
    await useDb();
    await pool.query(`
    INSERT INTO users (name,email,password,rol) VALUES
        ("normal","normal@normal.com", "$2b$10$wI9Xu9eWp/w.lm5Dv.43eu61axYgmw.Mz8Lqgi7CXdlat81lGkc.K","normal"),
        ("admin", "admin@admin.com","$2b$10$FaeJL0yg4H9pYQVTlcjvcePvtA4GQQAyHsJoH54OG.vGLWU8T3cGi", "admin")
      
    `);

    await pool.query(`
    INSERT INTO training (name, description,photo, typology, muscle_group, id_user) 
    VALUES 
    ('Press de Hombro', 'Para su ejecución comenzaremos sentados en un banco, con la espalda bien recta y tomaremos en ambas manos una mancuerna. Llevaremos las mismas a la altura de los hombros por los laterales del cuerpo mientras flexionamos los codos y las palmas de la mano miran hacia adelante.
    Desde los hombros inspiramos y elevamos las mancuernas hasta estirar los brazos hacia arriba, verticalmente. Espiramos al finalizar el movimiento mientras iniciamos el descenso a la posición inicial.Este ejercicio puede ejecutarse de pie, aunque generalmente se realiza sentado y puede incluirse un respaldo para evitar la curvatura de la espalda durante el ejercicio. También puede realizarse alternando los dos brazos.','press-hombro.png', 'Fuerza', 'Hombro',2),
    ('Elevaciones Laterales', 'Para comenzar el ejercicio debemos colocarnos de pie, con las piernas ligeramente flexionadas y separadas del ancho de la cadera. La espalda debe permanecer recta y en cada mano debemos sujetar una mancuerna, mientras los brazos permanecen a los lados del cuerpo o delante de los muslos, levemente flexionados.
    Tomando aire elevamos las mancuernas hasta que los brazos queden alineados con los hombros y desde allí bajamos lentamente mientras exhalamos.Las elevaciones laterales se pueden hacer con ambas manos juntas o también, alternando un brazo y otro. También puede efectuarse con poleas.','elevaciones-laterales.png', 'Fuerza', 'Hombro',2),
    ('Elevaciones Frontales', 'Para comenzar el movimiento debemos colocarnos de pie, con los pies ligeramente separados y mancuernas asidas con las manos en pronación o palmas hacia abajo, es decir, con el dorso de la mano mirando hacia afuera y los dedos hacia el cuerpo.
    Las mancuernas deben apoyarse junto a las manos sobre los muslos, ligeramente hacia los costados. Inspiramos y comenzamos a contraer los músculos para elevar un brazo hacia adelante mientras espiramos el aire.
    ','elevaciones-frontales.png', 'Fuerza', 'Hombro',2),
    ('Sentadilla', 'La sentadilla o squat es un movimiento que se inicia de pie, mirando al frente y con la espalda recta, mientras los pies se separan del ancho de los hombros.
    La barra utilizada debe situarse justo encima de los trapecios, no debe apoyarse en el cuello.
    Siempre mirando al frente y sin curvar la espalda, debemos descender los glúteos flexionando la rodilla y la cadera,  y cuidando que la rodilla no pase de la punta del pie ni sobrepase los 90 grados de flexión. Descendemos hasta que los muslos quedan paralelos al suelo y desde allí debemos elevarnos lentamente mientras exhalamos el aire inhalado al comenzar el descenso del cuerpo.Podemos hacer la sentadilla sin peso o en máquina para un recorrido guiado. También se pueden usar otro tipo de cargas o resistencias al realizar el movimiento, por ejemplo, mancuernas, gomas u otros.','sentadilla.png', 'Fuerza', 'Pierna',2),
    ('Abs con Mancuerna','El primer ejercicio de abdominales con una mancuerna es la plancha tradicional a la que le añadimos un movimiento extra. Desde la posición de plancha, desplaza la mancuerna a uno y otro lado, eso hará que tengamos que estar apoyados a una mano, y además que tengamos que aplicar una fuerza extra.','abs-mancuerna.png','Fuerza','Abdomen',2),
    ('Aperturas','Para comenzar el ejercicio debemos sentarnos en la máquina específica: la contractora de pecho, habiendo seleccionado previamente el peso a movilizar y ubicado el asiento de manera tal que los codos queden a igual altura que los hombros al situar los primeros sobre los cojines. Colocamos los brazos perpendiculares al torso y flexionamos los codos de manera que entre brazos y antebrazos se forme un ángulo recto. Con las muñecas relajadas, comenzamos el movimiento.Inspiramos e iniciamos desde los codos el movimiento. Mientras espiramos empujamos hacia adentro hasta que los brazos se cierren delante nuestro mediante la contracción del pectoral. Lentamente regresamos a la posición inicial.','aperturas-pecho.png','Fuerza','Pecho',2),
    ('Spinning','El spinning es una forma dinámica y efectiva de ejercicio cardiovascular que se realiza en bicicletas estacionarias especialmente diseñadas. Durante una sesión de spinning, los participantes pedalean al ritmo de la música, guiados por un instructor o a través de una aplicación de gimnasio. Ajustando la resistencia de la bicicleta, los usuarios pueden simular diversas condiciones de terreno y personalizar la intensidad de su entrenamiento. Esta actividad no solo fortalece las piernas y mejora la resistencia cardiovascular, sino que también ofrece una experiencia motivadora y social, ya que los participantes pueden disfrutar de entrenamientos en grupo. ¡Descubre el poder del spinning para alcanzar tus metas de acondicionamiento físico de manera divertida y efectiva!','bici-spinning.png','Cardio','Full body',2),
    ('Correr en Cinta','Descubre la libertad de correr en nuestra aplicación de gimnasio desde la comodidad de tu hogar. Nuestras sesiones de correr en cinta te permiten personalizar tu entrenamiento a tus propios términos. Ajusta la velocidad y la inclinación según tus objetivos de fitness, mientras sigues tus propios ritmos o te sumerges en entrenamientos emocionantes guiados por instructores expertos. Experimenta la sensación de correr al aire libre en un entorno controlado y cómodo. Superar tus límites nunca ha sido tan accesible. ¡Prepárate para elevar tu rutina de running con nuestras sesiones de correr en cinta en la app de gimnasio, donde la motivación y el rendimiento se encuentran al alcance de un clic','cinta-correr.png','Cardio','Full body',2),
    ('Crunch','Para comenzar el movimiento necesitamos un fitball o pelota suiza, sobre la cual debemos apoyar nuestra espalda. Con los pies apoyados en el piso, las rodillas flexionadas a 90 grados y las manos detrás y a los lados de la cabeza, iniciamos el ejercicio.
    Desde atrás, con la espalda casi en su totalidad apoyada sobre el fitball excepto la cabeza y columna dorsal que deben estar levemente despegadas del objeto, inspiramos y mientras exhalamos el aire iniciamos el encogimiento abdominal para elevar el torso mediante la contracción de los músculos de la zona media del cuerpo.Regresamos lentamente a la posición inicial y repetimos tantas veces como necesitemos para completar la serie de ejercicios que nos han indicado.
    ','crunch.png','Fuerza','Abdomen',2),
    ('Curl con Barra','Para comenzar el movimiento debemos comenzar de pie, con la espalda recta, las rodillas ligeramente flexionadas y los pies separados del ancho de los hombros.
    Tomaremos una barra con las manos, de manera que las palmas miren hacia arriba, es decir, con agarre en supinación. Las manos deben estar separadas en la barra un poco más allá de la anchura de los hombros.Desde esta posición, sin movilizar el tronco y manteniendo los codos a los lados del cuerpo, debemos inspirar y flexionar los codos mientras acercamos la barra al pecho y contraemos glúteos, abdominales y espinales para no mover el tronco.Espiramos al final del movimiento y descendemos lentamente la barra hasta la posición inicial.','curl-barra.png','Fuerza','Biceps',2),
    ('Curl con Mancuerna','Al sentarnos en un banco inclinado y agarrar unas mancuernas nuestros brazos van a quedar colgando con los codos por detrás del tronco. Desde esa posición fija los codos y realiza el curl de bíceps sin moverlos. Utiliza diferentes inclinaciones y así el punto donde el ejercicio te cuesta más irá variando según la inclinación.','curl-mancuerna.png','Fuerza','Biceps',2),
    ('Curl Agarre Martillo','Para comenzar el ejercicio nos colocaremos de pie con las rodillas levemente flexionadas y una mancuerna en cada mano, tomadas de manera tal que las palmas se miren entre ellas. Con la espalda recta e intentando no movilizar el brazo y codo sino únicamente el antebrazo, inspiramos y realizamos una flexión de codo con uno de los brazos, conservando la posición de las manos.
    Las palmas de las manos deben mirar hacia el cuerpo durante todo el recorrido para simular un martillo que sube y baja con la flexión del codo.Espiramos al final del movimiento y descendemos de manera controlada el peso para efectuar la flexión de codo con el otro brazo y así sucesivamente realizamos el curl de bíceps.
    El curl de bíceps tipo martillo se puede realizar alterno como hemos descrito o bien, simultáneamente de ambos lados del cuerpo.','curl-martillo.png','Fuerza','Biceps',2),
    ('Dominadas','Para comenzar a hacer una dominada correctamente debes iniciar el movimiento colgándote de la barra de dominadas con ambas manos usando un banco y no saltando y colgándote ya que seguramente no te agarrarás como debes. Separa los brazos algo más de la anchura de tus hombros, aunque para mejorar y trabajar diferentes ángulos de tus dorsales y trapecios puedes variar la separación entre cada mano.
    El agarre típico de una dominada es pronado, es decir, con las palmas de las manos mirando hacia fuera, tal y como se agarra en el vídeo. También existe el agarre supinado, es decir con las palmas de tus manos se dirijan hacia ti para proporcionar estímulos diferentes a los músculos de la espalda, pero así se tira mucho más de bíceps y el ejercicio es mucho más sencillo.Una vez estés colgado de la barra es importante extender los brazos por completo y relajar los hombros para que los dorsales queden totalmente estirados. Esto es importante porque es un fallo que hemos visto cantidad de veces en no estirarse desde un principio para hacerse trampas a uno mismo. Pues no, lo ideal y correcto es estirarse desde el inicio del ejercicio.
    Inspira profundamente y aguanta la respiración mientras contraes los dorsales para elevarte hacia arriba lentamente, con los codos a los lados y hacia afuera, sin ayudarte con las piernas subiéndolas, así que mantenlas quietas todo el rato. Debes hacer la subida más rápido que la bajada e intenta hacer una pequeña parada en la posición más alta, que es cuando la barbilla sobrepasa la barra. No es una dominada completa si no la superas, así que debes realizar el movimiento completo para contarla como tal y sin echar la cabeza hacia atrás para que la barbilla pase antes.','dominadas.png','Fuerza','Espalda',2),
    ('Elíptica','Sumérgete en una experiencia de entrenamiento de cuerpo completo con nuestras sesiones de elíptica en la aplicación de gimnasio. La elíptica ofrece un ejercicio suave y de bajo impacto que combina el movimiento de piernas y brazos, ayudándote a tonificar músculos y quemar calorías de manera eficiente. Sigue nuestras sesiones guiadas por instructores expertos o personaliza tu propio ritmo. Ajusta la resistencia para adaptar el desafío a tu nivel de condición física. Disfruta de la música motivadora y sumérgete en una sesión de cardio que transformará tu rutina de ejercicios. ¡Descubre los beneficios de la elíptica en nuestra app de gimnasio y lleva tu fitness a nuevos niveles de energía y bienestar!','eliptica.png','Cardio','Full body',2),
    ('Extensión de Triceps','Para comenzar este ejercicio debemos posicionarnos de pie frente al aparato de polea alta, y habiendo seleccionado el peso a utilizar, debemos tomar con las manos el mago de manera que las palmas miren hacia el suelo. Con los brazos pegados al torso y los codos siempre alineados con el cuerpo, comenzamos el movimiento.
    Realizamos una extensión de los codos, llevando el mango de la polea hacia abajo, sin despegar los codos de los lados del cuerpo y únicamente movilizando el antebrazo. Espiramos al final del movimiento y regresamos lentamente a la posición inicial.','extension-triceps.png','Fuerza','Triceps',2),
    ('Flexiones','Empezamos con las manos plantadas en el suelo directamente debajo de los hombros con una amplitud ligeramente superior a estos. En la parte trasera apoyamos los dedos de los pies con los pies juntos y las piernas estiradas para estabilizar el movimiento. El core debe estar activo durante todo el movimiento para mantener la línea recta y la estabilidad del cuerpo.Manteniendo esta línea recta flexionamos los brazos y bajamos el cuerpo hasta que el pecho llegue a apoyarse en el suelo y, mientras bajamos, la cabeza debe mirar ligeramente hacia adelante como a unos tres metros de distancia. También es importante mantener los codos pegado al cuerpo para que el tríceps trabaje.
    Luego, una vez que el pecho toque el suelo, hacemos fuerza con los brazos y el pecho estirándolos por completo para terminar una repetición.','flexiones.png','Fuerza','Pecho',2),
    ('Fondo de Triceps','Colocar las manos sobre un banco o silla, separadas del ancho de los hombros.Desplazar los pies hacia adelante para separar la cola del banco o silla. Los pies deben apoyarse en el suelo separados del ancho de la cadera.Siempre debes mantener levemente flexionados los codos de manera de mantener constante la presión sobre los triceps.Lentamente debes flexionar los codos para bajar la parte superior del cuerpo hacia el suelo, hasta alcanzar un ángulo de 90 grados formado con los brazos. La espalda debe permanecer cerca del banco.Los codos deben mantenerse lo más cerca del torso posible y deben flexionarse hacia atrás, evitando que se desplacen hacia afuera durante el descenso, ya que el esfuerzo no se concentrará del todo en el triceps y puede sobrecargar la articulación del hombro.Se debe inspirar al descender el cuerpo mediante la flexión de codos y espirar al regresar a la posición inicial lentamente, empujando con fuerza el cuerpo hacia arriba.','extension-triceps-banco.png','Fuerza','Triceps',2),
    ('Máquina de Remo','Explora una forma única y efectiva de entrenamiento con nuestras sesiones de máquina de remo en la aplicación de gimnasio. La remadora proporciona un ejercicio de cuerpo completo que involucra piernas, brazos y core, mejorando la fuerza y la resistencia. Sigue nuestras sesiones guiadas por instructores virtuales o rema a tu propio ritmo mientras disfrutas de impresionantes paisajes virtuales. Ajusta la resistencia para adaptar la intensidad y desafía tus límites. La máquina de remo es ideal para fortalecer músculos, quemar calorías y mejorar tu salud cardiovascular. ¡Prepárate para remar hacia un nuevo nivel de fitness con nuestras sesiones de máquina de remo en la app de gimnasio, donde cada remada te acerca a tus metas de bienestar!','maquina-remo.png','Cardio','Full body',2),
    ('Pájaros','Para comenzar el ejercicio debemos colocarnos de pie con las piernas separadas del ancho de los hombros o poco menos y las rodillas ligeramente flexionadas. Con mancuernas asidas en ambas manos inclinamos el tronco hacia adelante manteniendo la espalda recta.
    Las manos deben colgar a los lados del cuerpo mientras los codos siempre se conservan levemente flexionados y desde allí, inspiramos para elevar los brazos hasta la horizontal de manera que queden paralelos al suelo, tal como si fuéramos un pájaro que despliega sus alas. Descendemos lentamente y espiramos al final del movimiento.
    ','pajaros.png','Fuerza','Espalda',2),
    ('Peso Muerto','Para realizar el peso muerto debemos colocarnos de pie frente a una barra situada en el suelo, con las piernas ligeramente separadas y las rodillas levemente flexionadas.
    Desde esta posición inicial debemos inclinar el tronco hacia adelante manteniendo la espalda recta y coger la barra con las manos mientras las palmas miran hacia el cuerpo, es decir, en pronación. Inspiramos y enderezamos el cuerpo, colocándonos en posición vertical nuevamente. Espiramos al final del movimiento.','peso-muerto.png','Fuerza','Pierna',2),
    ('Press de Pecho','Para iniciar la realización del ejercicio es necesario acostarse en un banco plano con los glúteos, caderas y hombros sobre el banco. Los pies deben apoyarse en suelo, separados un poco más allá del ancho de lo hombros. Con las manos debemos tomar la barra de manera que las palmas miren hacia adelante, es decir, en pronación, y separadas ligeramente más allá de la anchura de los hombros.
    El brazo y el antebrazo deben formar un ángulo de 90º, por lo que debemos flexionar el codo de manera que la barra tomada con las manos quede exactamente encima del pecho.Desde allí debemos inspirar y descender lentamente la barra hacia el pecho, sin despegar la espalda del banco. Una vez la barra esté sobre el pecho debemos empujar hacia arriba mientras espiramos y subimos lentamente los brazos.','press-pecho.png','Fuerza','Pecho',2),
    ('Remo con Barra','Para iniciar el movimiento debemos colocarnos de pie con las rodillas ligeramente flexionadas y el tronco inclinado formando con las piernas un ángulo de 45º. Con la espalda recta y la barra tomada en pronación, con las palmas hacia abajo, separamos las manos de la anchura de los hombros, y dejamos caer los brazos frente al torso.
    Des de allí inspiramos y efectuamos una contracción abdominal mientras tiramos la barra hacia el pecho para luego espirar y regresar lentamente hacia la posición inicial.','remo-con-barra.png','Fuerza','Espalda',2),
    ('Sentadilla Búlgara','Este ejercicio se relaciona con la fase de impulsión de la carrera, cuando extendemos la rodilla para dar la zancada. También con la fase de amortiguación cuando hacemos la bajada, evitando que nos "hundamos".
    Por un lado, trabajaremos la potencia de la zancada, sobre todo si ponemos peso extra y, por otro, trabajaremos la estabilidad y propiocepción de la pisada, al crearse cierto desequilibrio al tener solo un apoyo en suelo.
    ','sentadilla-bulgara.png','Fuerza','Pierna',2)
;
    `);

    console.log('Base de datos poblada.');
  } catch (error) {
    console.error(`Error al insertar los datos en la bbdd ${DB_NAME}`);
  } finally {
    process.exit();
  }
};

populateDb();
